Added Keyper introduction
RAPID-Platform-Projects/Rapid-Docs pull request #145
Opened 2024-04-12 02:42 UTC by MattFranklin-Rapid

2024-04-14 23:27 UTC, jinferno requested changes

2024-04-14 23:27 UTC, jinferno commented on docs/Rapid/4-Keyper Manual/1-Introduction/1-Introduction.md
> +The Rapid Platform is a highly customizable solution for managing business data. As a Keyper (a Key Person) you can customize your site to better reflect the business.
customisable
customise
_(since we're marketing ourselves as Australian)_

2024-04-14 23:27 UTC, jinferno commented on docs/Rapid/4-Keyper Manual/1-Introduction/1-Introduction.md
Great :) just two AUS spelling improvements

2024-04-14 23:32 UTC, PeterFranklin231 approved these changes
Nice, concise, useful.

2024-04-15 00:34 UTC, PeterFranklin231 approved these changes
Baeuteeful

2024-04-15 00:34 UTC, merged

2024-04-15 01:48 UTC, jinferno reviewed
Nice!