Adaptive connections v1
RAPID-Platform-Projects/Rapid-Docs pull request #188
Opened 2024-05-08 16:39 UTC by RapidVinay

This has the documentation of connections at document level. 
I will append the element level connection to this article shortly.

2024-05-08 18:18 UTC, thealexclub commented on docs/Rapid/4-Keyper Manual/4-Adaptive Designer/6-How to configure connection with data table/6-How to configure connection with data table.md
> +   a. **Source** - The source will be pre-selected here based on the parent.
Instead of Source, This is called the Connector.

2024-05-08 18:21 UTC, thealexclub commented on docs/Rapid/4-Keyper Manual/4-Adaptive Designer/6-How to configure connection with data table/6-How to configure connection with data table.md
> +   b. **Nature of connection** - Select View (if you want an array of items) or Single Item.
This is called the Method. The connection method is view. 

I like "Nature of connection" as an explanation, though. 
```suggestion
   b. **Method** - The method defines the nature of connection. Select View (if you want an array of items) or Single Item.  
```

2024-05-08 18:23 UTC, thealexclub commented on docs/Rapid/4-Keyper Manual/4-Adaptive Designer/6-How to configure connection with data table/6-How to configure connection with data table.md
> +  2. at the element level - the table column is connected to the element of the document.
Element level connections are only supported on legacy forms. They cannot be created in the v3 form designer.

2024-05-08 18:25 UTC, thealexclub requested changes
Looks great 🛩️ I've left a few comments about terminology.

2024-05-09 19:12 UTC, thealexclub approved these changes
Looks great, Thanks Vinay 😄

2024-05-15 04:14 UTC, MattFranklin-Rapid approved these changes
Nice! Everything builds and links work as expected

2024-05-15 04:15 UTC, merged